version: "3.8"

services:
  # Nombre del servicio: db (Database)
  db:
    # Usamos la imagen oficial de pgvector que ya trae Postgres 16 + extensi칩n vectorial instalada
    image: pgvector/pgvector:pg16
    container_name: arquibot_postgres
    restart: always
    # Configuraci칩n de credenciales (luego las leeremos de un archivo .env)
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # Mapeo de puertos: El 5432 del contenedor ser치 el 5432 de tu localhost
    ports:
      - "5432:5432"
    # Persistencia: Guardamos los datos en una carpeta local para no perderlos si apagamos el contenedor
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  # Opcional: pgAdmin (Interfaz gr치fica web para ver tu base de datos sin instalar nada)
  pgadmin:
    image: dpage/pgadmin4
    container_name: arquibot_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@arquibot.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
